import type { ComponentProps } from "react";
import {
  Archive,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BadgeDollarSign,
  BookOpen,
  BookOpenCheck,
  Bot,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  ChevronLeft,
  CircleCheck,
  Clock3,
  Coffee,
  Compass,
  CreditCard,
  Database,
  FileCheck2,
  Gift,
  GraduationCap,
  HeartHandshake,
  House,
  Landmark,
  Library,
  LogIn,
  Map,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  Newspaper,
  Plus,
  School,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  UserRound,
  UsersRound,
  Wallet,
  Wifi,
  X,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./nav-items";

const ICONS: Record<IconName, LucideIcon> = {
  house: House,
  compass: Compass,
  "user-round": UserRound,
  newspaper: Newspaper,
  bot: Bot,
  "log-in": LogIn,
  search: Search,
  sparkles: Sparkles,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  "file-check-corner": FileCheck2,
  "graduation-cap": GraduationCap,
  "map-pin": MapPin,
  "calendar-clock": CalendarClock,
  wallet: Wallet,
  "heart-handshake": HeartHandshake,
  "book-open": BookOpen,
  "map-pinned": MapPinned,
  coffee: Coffee,
  "badge-dollar-sign": BadgeDollarSign,
  "shield-check": ShieldCheck,
  "book-open-check": BookOpenCheck,
  library: Library,
  "credit-card": CreditCard,
  wifi: Wifi,
  "briefcase-business": BriefcaseBusiness,
  "users-round": UsersRound,
  school: School,
  map: Map,
  archive: Archive,
  landmark: Landmark,
  "clock-3": Clock3,
  "calendar-days": CalendarDays,
  "chevron-left": ChevronLeft,
  send: Send,
  plus: Plus,
  x: X,
  menu: Menu,
  "sliders-horizontal": SlidersHorizontal,
  database: Database,
  megaphone: Megaphone,
  "arrow-up-right": ArrowUpRight,
  "circle-check": CircleCheck,
  gift: Gift,
};

export function Icon({
  name,
  ...props
}: { name: IconName } & Omit<ComponentProps<LucideIcon>, "ref">) {
  const Cmp = ICONS[name];
  return <Cmp aria-hidden {...props} />;
}
